### ISSUE TITLE
Latest version JRE 1.7 requirement

### ISSUE THREAD

**Issue by dgonsan** [OWASP/java-html-sanitizer#50]
The version released yesterday 20151202.1 has a new class AutoCloseableHtmlStreamRenderer that implements java.lang.AutoCloseable interface define on org/owasp/html/HtmlStreamRenderer.java. This change causes that the library depends on runtime on JRE 1.7 or greater throwing a ClassDefNotFound exception is used with lower versions.

Is this a mistake or form this version the library will require JRE 1.7?

**Comment by isun** [comment]
Which version is compatible with jre1.6? without the java.lang.autoclosable impl.

**Comment by val1984** [comment]
Autocloseable has been added in commit 42e7d5ffad201a983762c2fc57daf2876a6f068c which is weird since commit comment is "IDE warning cleanup".

**Comment by dgonsan** [comment]
We were using 20150501.1 and since the issue we have changed the pom to force that version an it is working fine with JRE 1.6

**Comment by jmanico** [comment]
I *think* this is now resolved. I am going to close this but if I closed it improperly please say something and I'll fix. Thanks folks.

**Comment by volkertb** [comment]
I've encountered this problem again in version 20160614.1. The AutoCloseableHtmlStreamRenderer is present again, but oddly enough, it only makes the code fail at run-time. Also I'm surprised how the owasp-java-html-sanitizer dependency made it through our project's Maven bytecode enforcer rule, which explicitly forbids any dependencies that were compiled to a bytecode higher than version 50 (Java 6). I guess it's a source-only dependency? It apparently compiles fine with a Java 6 compiler, and generates proper Java 6 bytecode, even though it has a source code dependency on AutoCloseable??? What kind of voodoo is this? :-O

**Comment by mikesamuel** [comment]
@volkertb, do you have a stack trace handy?

**Comment by volkertb** [comment]
@mikesamuel @jmanico I get the stacktrace below in a unit test at the point when it invokes the sanitize method an a PolicyFactory instance. I've tested this with the following versions, starting with the version mentioned by @dgonsan:

20150501.1 -> Tests pass fine.
20151202.2 -> Tests fail with the stacktrace below.
20160203.1 -> Tests fail with the stacktrace below.
20160614.1 -> Tests fail with the stacktrace below.

The stacktrace in question:

java.lang.NoClassDefFoundError: java/lang/AutoCloseable
        at java.net.URLClassLoader$1.run(URLClassLoader.java:200)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:281)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:56)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:195)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
        at org.owasp.html.PolicyFactory.sanitize(PolicyFactory.java:123)
        at org.owasp.html.PolicyFactory.sanitize(PolicyFactory.java:101)

**Comment by mikesamuel** [comment]
Thanks.  Will look into it tomorrow AM (US EST).

**Comment by volkertb** [comment]
@mikesamuel I suspect that the reason why this issue was missed both by you and by my colleague is because the problem only manifests itself when the code is **run** (not just compiled) on an actual Java 6 JVM. As it is, the code builds fine on JDK 6, and it also runs fine on JDK 7. A proper way to test this theory and to create an automated regression test for this issue going forward may be the following:

Introduce the use of Maven Toolchains in the POM of java-html-sanitizer. The Toolchains feature allows you to make a distinction between the JDK version on which you are running Maven itself and the JDK version that you actually compile the code with. This will also allow you to build the code and run the unit tests on an older JDK version even with newer Maven versions that do no longer work on JDK 6. For details on this feature, see https://maven.apache.org/guides/mini/guide-using-toolchains.html
Add a Maven profile that demands a JDK 6 (1.6) toolchain (which will then automatically be used byboth the Maven Compiler Plugin and the Maven Surefire and Failsafe Plugins) and add a separate job on your CI server that both builds the project and, very crucially, also runs the unit tests using this profile. Label this CI job something like "java-html-sanitizer with Java 6".
If you want to be even more future proof, do the same for JDK 7 and JDK 8, so you have separate Maven profiles for each major Java version. That way, you actually both compile the code and run the unit tests using all three JDK versions.

Note that introducing the use of Maven Toolchains will also require the existence of a well-defined toolchains.xml file in the ~/.m2 or %USERPROFILE%\.m2 folder (depending on OS) in any environment on which the code is to be built and unit-tested. This goes for both the CI server and for everyone working on this project. For more info, see the link to the official Maven Toolchains documentation that I mentioned further above.

This way, you should be able to catch compatibility errors (both **compile-time** and **run-time**) early from now on.

Please let me know if you need any help in setting this up. I happen to have some experience with this and I would be glad to help out. :-)

**Comment by jmanico** [comment]
> Please let me know if you need any help in setting this up. I happen
to have some experience with this and I would be glad to help out. :-)

Bring It On! :) Thanks for this excellent advice.

Aloha, Jim


On 6/26/16 10:32 PM, Volkert de Buisonjé wrote:
>
> @mikesamuel <https://github.com/mikesamuel> I suspect that the reason
> why this issue was missed both by you and by my colleague is because
> the problem only manifests itself when the code is *run* (not just
> compiled) on an actual Java 6 JVM. As it is, the code builds fine on
> JDK 6, and it also runs fine on JDK 7. A proper way to test this
> theory and to create an automated regression test for this issue going
> forward may be the following:
>
> Introduce the use of Maven Toolchains in the POM of
> java-html-sanitizer. The Toolchains feature allows you to make a
> distinction between the JDK version on which you are running Maven
> itself and the JDK version that you actually compile the code with.
> This will also allow you to build the code and run the unit tests on
> an older JDK version even with newer Maven versions that do no longer
> work on JDK 6. For details on this feature, see
> https://maven.apache.org/guides/mini/guide-using-toolchains.html
> Add a Maven profile that demands a JDK 6 (1.6) toolchain (which will
> then automatically be used byboth the Maven Compiler Plugin and the
> Maven Surefire and Failsafe Plugins) and add a separate job on your CI
> server that both builds the project and, very crucially, also runs the
> unit tests using this profile. Label this CI job something like
> "java-html-sanitizer with Java 6".
> If you want to be even more future proof, do the same for JDK 7 and
> JDK 8, so you have separate Maven profiles for each major Java
> version. That way, you actually both compile the code and run the unit
> tests using all three JDK versions.
>
> Note that introducing the use of Maven Toolchains will also require
> the existence of a well-defined toolchains.xml file in the ~/.m2 or
> %USERPROFILE%.m2 folder (depending on OS) in any environment on which
> the code is to be built and unit-tested. This goes for both the CI
> server and for everyone working on this project. For more info, see
> the link to the official Maven Toolchains documentation that I
> mentioned further above.
>
> This way, you should be able to catch compatibility errors (both
> *compile-time* and *run-time*) early from now on.
>
> Please let me know if you need any help in setting this up. I happen
> to have some experience with this and I would be glad to help out. :-)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/OWASP/java-html-sanitizer/issues/50#issuecomment-228684439>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAgcCRdTnT7-pz1oV99iGjJfKyGTm-QRks5qP4qUgaJpZM4Gt-I1>.
>

-- 
Jim Manico
Manicode Security
https://www.manicode.com

**Comment by volkertb** [comment]
@jmanico And thank you all for this very useful and important library! :+1: :-) If you'd like, I could try to have a go at it and offer you a pull request, but to be honest, it will be at least a month before I can get around to it (if that). I'm swamped in work right now... No promises, but I'll see what I can do. It would be great if I could contribute something to this project.

**Comment by mikesamuel** [comment]
https://github.com/OWASP/java-html-sanitizer/commit/74c6dd0247ea8c676aa8ce9db8c1497db2763aa5 should address this.

I'm used to environments where one builds all ones dependencies for the local architecture, so my first attempt forked architectures made sure that building on Java1.8 would produce classes that ran well on Java1.8 and building on Java1.6 would similarly work.
I build on Java1.8 for maven central pushes, so forking on architecture didn't helped.

I got over my reluctance to resort to reflection, so on JVMs where `java.io.Closeable` has `java.lang.AutoCloseable` as a super-interface, then certain wrapper classes will use reflection to close AutoCloseables that are not Closeables, and when that is not the case, only Closeable chaining will work.

**Comment by mikesamuel** [comment]
I committed changes which I think fix this issue.  If you're in a position
to test snapshot builds, go ahead and do that.  If not, I'll push to
central since I'm reasonably confident the issue is finally laid to rest.

**Comment by jmanico** [comment]
No problem at all, thanks for giving us good input. That alone is good
contribution. :)

Aloha, Jim

**Comment by jmanico** [comment]
This seems like a fully resolved issue with fixes committed to master. Nice work Mike! If this is still a problem please re-open. Thank you!
